### ISSUE TITLE
"Concurrent map read and map write" error when generating large datasets

### ISSUE THREAD

**Issue by sodle** [coccyx/gogen#15]
I'm attempting to generate a large dataset using the following command:
`gogen -c examples/weblog/weblog.yml -ot raw -o stdout gen -c 1 -i 1 -b -365d -e now`

A few hundred thousand events in, gogen crashes with the attached stack trace.
[gogen_error.txt](https://github.com/coccyx/gogen/files/1001889/gogen_error.txt)

**Comment by coccyx** [comment]
Thank you so much for the bug report! I have reproduced and fixed this. Let me know if you see any further issues.
