### ISSUE TITLE
Ubuntu 16.04 Invalide memory address ornil pointer derefence

### ISSUE THREAD

**Issue by trailhounds9002** [coccyx/gogen#16]
In attempting to use gogen I received this error. Please help me resolve this, as event-generator doesn't want to play, and this seems as if it is a better solution anyway!

-----------------

gogen search weblog
Returning results for search: "weblog"

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4c551a]

goroutine 1 [running]:
panic(0x8dcc20, 0xc420016150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli%2ev1.HandleAction.func1(0xc4200f7258)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli.v1/app.go:473 +0x29e
panic(0x8dcc20, 0xc420016150)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/coccyx/gogen/internal.listsearch(0xc420117380, 0x27, 0x21, 0xc4200e5a90, 0x6)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/internal/gogen.go:48 +0xba
github.com/coccyx/gogen/internal.Search(0xc4200e5a90, 0x6, 0xc4200f6d68, 0x1, 0x1)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/internal/gogen.go:41 +0x87
main.main.func6(0xc42008f180, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/main.go:318 +0x1c4
reflect.Value.call(0x8c10a0, 0x9ab080, 0x13, 0x961f51, 0x4, 0xc4200f7218, 0x1, 0x1, 0x4de6a8, 0x952260, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x8c10a0, 0x9ab080, 0x13, 0xc4200f7218, 0x1, 0x1, 0x0, 0xc4200f71f8, 0x4e1df6)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x8c10a0, 0x9ab080, 0xc42008f180, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli.v1/app.go:482 +0x1e0
github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x962eb3, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x967ef1, 0x11, 0x0, ...)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli.v1/command.go:186 +0xc26
github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420118000, 0xc42000c390, 0x3, 0x3, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/vendor/gopkg.in/urfave/cli.v1/app.go:235 +0x60c
main.main()
	/home/ubuntu/.go_workspace/src/github.com/coccyx/gogen/main.go:510 +0x14ee

uname -a:
Linux snoopy 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ulimit -a
address space limit (Kibytes)  (-M)  unlimited
core file size (blocks)        (-c)  0
cpu time (seconds)             (-t)  unlimited
data size (Kibytes)            (-d)  unlimited
file size (blocks)             (-f)  unlimited
locks                          (-x)  unlimited
locked address space (Kibytes) (-l)  64
message queue size (Kibytes)   (-q)  800
nice                           (-e)  0
nofile                         (-n)  1024
nproc                          (-u)  110939
pipe buffer size (bytes)       (-p)  4096
max memory size (Kibytes)      (-m)  unlimited
rtprio                         (-r)  0
socket buffer size (bytes)     (-b)  4096
sigpend                        (-i)  110939
stack size (Kibytes)           (-s)  8192
swap size (Kibytes)            (-w)  not supported
threads                        (-T)  not supported
process size (Kibytes)         (-v)  unlimited

ldd bin/gogen
	linux-vdso.so.1 =>  (0x00007ffddc285000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7fa8fe4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7fa8c1a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7fa9201000)

free
              total        used        free      shared  buff/cache   available
Mem:       28448768     9079212    17745176      161152     1624380    18528972
Swap:      27343868           0    27343868

**Comment by df-dev** [comment]
I am experiencing the same error

**Comment by coccyx** [comment]
Missed the earlier bug report. I'll take a look this weekend!

**Comment by coccyx** [comment]
Can't reproduce. Is this only on `gogen search` or you get this error for every command?
