### ISSUE TITLE
Error reported when endpoint returns "201 Created"

### ISSUE THREAD

**Issue by blelem** [coccyx/gogen#17]
When sending http requests to Azure event hub, gogen prints out an error even though the request was succesful. The end-point returns an http status of "201 Created", instead of the more standard "200 OK".
This is what the error looks like:

> ERROR Error making request from sample 'tutorial1' to endpoint 'https://XX.servicebus.windows.net/XXX/messages', status '201':  file=http.go func=outputter.(*httpout).newPost.func1 line=98

This is a fairly minor annoyance, as gogen prints the error message and then continues doing its normal business.

**Comment by coccyx** [comment]
Thanks so much for the bug report! I fixed this in the current build.
