### ISSUE TITLE
Dispalying Mix output as a single json

### ISSUE THREAD

**Issue by minnumerinalex** [coccyx/gogen#20]
Is it possible to display the the output from different yml file given in mix as a single json?
example when i added two yml files in mix and execute,i am getting the output as below:
{"name" : "samples",
"age" : "54"}
{"Height":"164cm","Weight":"54kg"} 

what i need is either {"name" : "samples","age" : "54","Height":"164cm","Weight":"54kg"} 
or
[{"name" : "samples",
"age" : "54"},
{"Height":"164cm","Weight":"54kg"} ]
ie a valid json format.

**Comment by coccyx** [comment]
Mixes are designed to create a data stream full of different types of events/documents. The idea is that a sample creates events/documents with each time interval generating count documents. It was not designed to combine multiple samples together. This is impractical given the internal structure of Gogen, where each sample gets its own timer thread which generates jobs for the generator workers to perform.
