### ISSUE TITLE
Add support for local config files

### ISSUE THREAD

**Issue by skywalka** [coccyx/gogen#37]
Hi,

Firstly, I'm a big fan of gogen... thanks heaps for making an awesome log generator!

I just wanted to ask if it would be possible to add support for local config files as some customers don't have outbound internet access in their environments.

For example, I would like to run the following:
# gogen -c ./weblog
FATA[0000] error retrieving gogen config for gogen './weblog'  error="Error retrieving Gogen ./weblog: Get https://api.gogen.io/v1/get/./weblog: Forbidden" file=share.go func=internal.PullFile line=255

Cheers,

Luke.

**Comment by coccyx** [comment]
This works today. This needs to be named `weblog.yml`.

**Comment by skywalka** [comment]
Ah nice!

This works like a treat:

gogen -c ./examples/weblog/weblog.yml
