### ISSUE TITLE
Gogen replay mode with "begin" time

### ISSUE THREAD

**Issue by pstnslv** [coccyx/gogen#39]
When I start the "replay" generator with "begin" time, the interval of the output events is shifted. I was surprised that even in generator tests such a shift is provided for:
In sample (gogen / tests / replay / fullreplay.yml)
    - "_raw": "2001-10-20T12: 00: 00"
    - "_raw": "2001-10-20T12: 00: 01"
    - "_raw": "2001-10-20T12: 00: 06"
    - "_raw": "2001-10-20T12: 00: 16"
    - "_raw": "2001-10-20T12: 00: 36"
But in output test (gogen / tests / replay_test.go)
2001-10-20T12: 00: 00
2001-10-20T12: 00: 13
2001-10-20T12: 00: 14
2001-10-20T12: 00: 19
2001-10-20T12: 00: 29

All interval in output are shifted, and one of them (20 sec) is missing.

Please help, is this a bug or I can fix it with the Gogen settings?

**Comment by coccyx** [comment]
I built it that way seemingly on purpose but I can't remember why I did. I have corrected it to where replay works according to my current expectations, which is that it proceeds with timestamps the same as in the original data.

This is fixed in v0.10.3, which is on the CDN now.

**Comment by pstnslv** [comment]
Hi Clint!

You are great man, thanks a lot for your work!

With best regards,
Stanislav Prishchep

вс, 23 февр. 2020 г. в 02:26, Clint Sharp <notifications@github.com>:

**Comment by pstnslv** [comment]
Hello Clint,

Sorry to bother you, but I becoming an active Gogen user. Now I try to
using it for replay daily log files for SIEM testing and demonstrations
purposes. I have a daily log (from 00:00:00 to 23:59:59) I'd like to start
it at specific begin time to replay, and don't stop replay to simulate
normal daily user behavior in real time. I'd like to use it for machine
learning study.
But I don't understand, which interval Gogen use between the last and the
first events (after the sample file ends and Gogen replay it again).
The sample:
  "@timestamp":"2020-02-17T08:00:00.000Z"
  "@timestamp":"2020-02-17T08:00:10.000Z"
  "@timestamp":"2020-02-17T08:00:30.000Z"

The output:
"@timestamp":"2020-02-24T16:11:24.517Z"
"@timestamp":"2020-02-24T16:11:34.518Z
"@timestamp":"2020-02-24T16:11:54.519Z"
"@timestamp":"2020-02-24T16:12:07.021Z"
"@timestamp":"2020-02-24T16:12:17.021Z"
...

Can I tell Gogen to start replay the sample file after specified period
(like 1 minute for example above) or 24h for my daily log file?
Or maybe it is a bug, and interval between 3-th and 4-rh events need to be
30 sec (on this example)
Could you help?

With best regards,
Stanislav Prishchep


пн, 24 февр. 2020 г. в 13:28, Stanislav Prischep <pv.stanislav@gmail.com>:
